#!/bin/bash
# Build the freebootin.com website and produce an easy to upload archive.

main() {
  local BASEDIR=$(pwd)
  local TMPDIR="${BASEDIR}/tmp"
  local REF=$(stat -c %Y ${BASEDIR}/ref)
  echo ${REF}

  mkdir "${TMPDIR}"

  for dir in ${BASEDIR}/site/*/; do
    echo "Building " $(basename ${dir}) "..."
    pandoc \
      --output="${TMPDIR}/$(basename ${dir}).html" \
      --template="${BASEDIR}/templates/article.html" \
      --standalone "${dir}README.md"

# TODO move non-README.md archiving to serperate function
#     for file in ${dir}*; do
#       if [[ ${file} != "README.md" ]]; then
#         cp ${file} "${TMPDIR}"
#       fi
#     done
  done

  echo "Adding common files to archive..."
  cp "${BASEDIR}"/common/* "${TMPDIR}"

  echo "Creating archive..."
  cd "${TMPDIR}" 
  tar cfz ../upload.tar.gz *
  cd - > /dev/null

  echo "Cleaning up..."
  rm -r "${TMPDIR}"

  echo "Done"
}

main
