#!/bin/bash
# Build the freebootin.com website and produce an easy to upload archive.

main() {
  local LOCAL_COPY=""
  local BASEDIR=$(pwd)
  local TMPDIR="${BASEDIR}/tmp"
  local REF=$(stat -c %Y ${BASEDIR}/ref)

  while getopts "hl" option; do
    case $option in
      h) # display help
        echo "Help message"
        ;;
      l) # build local copy
        LOCAL_COPY=TRUE
        ;;
      \?) # everything else
        echo "Invalid option passed."
        ;;
    esac
  done

  echo ${REF}

  mkdir "${TMPDIR}"

  for dir in ${BASEDIR}/site/*/; do
    echo "Building " $(basename ${dir}) "..."
    pandoc \
      --output="${TMPDIR}/$(basename ${dir}).html" \
      --template="${BASEDIR}/templates/article.html" \
      --standalone "${dir}README.md"

# TODO move non-README.md archiving to serperate function
#     for file in ${dir}*; do
#       if [[ ${file} != "README.md" ]]; then
#         cp ${file} "${TMPDIR}"
#       fi
#     done
  done

  echo "Adding common files to archive..."
  cp "${BASEDIR}"/common/* "${TMPDIR}"

  echo "Creating archive..."
  cd "${TMPDIR}" 
  tar cfz ../upload.tar.gz *
  cd - > /dev/null

  if [[ -n $LOCAL_COPY ]]; then
    echo "Saving local copy to ${TMPDIR}"
    echo "Done"
    exit 0
  fi

  echo "Cleaning up..."
  rm -r "${TMPDIR}"

  echo "Done"
  exit 0
}

main $@
