#!/bin/bash
# Build the freebootin.com website and produce an easy to upload archive.

main() {
  local BASEDIR="/home/patrick/repos/freebootin/freebootin-dot-com"
  local TMPDIR="${BASEDIR}/tmp"
  mkdir "${TMPDIR}"

  for dir in ${BASEDIR}/site/*/; do
    echo "Building " $(basename ${dir}) "..."
    pandoc \
      --output="${TMPDIR}/$(basename ${dir}).html" \
      --template="${BASEDIR}/templates/article.html" \
      --standalone "${dir}README.md"
  done

  echo "Creating archive..."
  cd "${TMPDIR}" 
  tar cfz ../upload.tar.gz *
  cd - > /dev/null

  echo "Cleaning up..."
  rm -r "${TMPDIR}"

  echo "Done"
}

main
